version: '3.8'

services:
  horror:
    networks:
      - horror_core
    container_name: api-quest-house
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&:
             uvicorn horror_core.asgi:application --host 0.0.0.0"
    expose:
      - '8000'
    environment:
      - VIRTUAL_HOST=api.boxy.skillbox.by
      - LETSENCRYPT_HOST=api.boxy.skillbox.by
      - LETSENCRYPT_EMAIL=lol@gmail.com
      - TZ=Europe/Moscow   
#    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

networks:
  horror_core:
    driver: bridge
