services:
  db:
    image: postgres:15
    container_name: backend-postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /root/cms/storage/backend/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    networks:
      - horror_core

  horror:
    networks:
      - horror_core
    container_name: api-quest-house
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             uvicorn horror_core.asgi:application --host 0.0.0.0"
    expose:
      - '8000'
    environment:
      - VIRTUAL_HOST=api.quest-house.by
      - LETSENCRYPT_HOST=api.quest-house.by
      - LETSENCRYPT_EMAIL=1@1.com
      - TZ=Europe/Moscow
    volumes:
      - ./media:/horror_core/media
    env_file:
      - .env
    restart: unless-stopped

  tg_bot:
    build: .
    command: python telegram.py
    depends_on:
      - horror
      - db
    restart: unless-stopped
    networks:
      - horror_core


networks:
  horror_core:
    driver: bridge



