# Generated by Django 5.1.7 on 2025-03-19 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название квеста')),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата регистрации квеста')),
                ('novelty', models.BooleanField(default=False, verbose_name='Новинка или нет')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание квеста')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация квеста')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг квеста')),
                ('travel_time', models.IntegerField(default=60, verbose_name='Примерное время, для прохождение квеста')),
                ('fear', models.IntegerField(default=0, verbose_name='Уровень страха')),
                ('complexity', models.IntegerField(default=0, verbose_name='Уровень сложности')),
                ('count_players', models.CharField(max_length=30, verbose_name='Ограничения игроков для квеста')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр квеста')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Правила посещения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность квеста')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='horrors/')),
                ('horror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app_horror.horror')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата бронирования ')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('certificate', models.BooleanField(default=False, verbose_name='Наличие сертификата')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий клиента')),
                ('horror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app_horror.horror', verbose_name='Квест для брони')),
                ('slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='app_horror.timeslot', verbose_name='Дата-время брони')),
            ],
        ),
    ]
