# Generated by Django 5.1.7 on 2025-03-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена за квест'),
        ),
    ]
