# Generated by Django 5.1.7 on 2025-03-24 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0002_booking_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundPhotoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='horrors/background_photo_card/')),
                ('horror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_back_card', to='app_horror.horror')),
            ],
        ),
        migrations.CreateModel(
            name='BlurPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='horrors/blur/')),
                ('horror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_blur', to='app_horror.horror')),
            ],
        ),
    ]
