# Generated by Django 5.1.7 on 2025-05-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0003_backgroundphotocard_blurphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='app_horror.timeslot', verbose_name='Дата-время брони'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('data', 'slot')},
        ),
    ]
