# Generated by Django 5.1.6 on 2025-06-23 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0004_alter_booking_slot_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирование'},
        ),
        migrations.AlterModelOptions(
            name='horror',
            options={'verbose_name': 'Квесты', 'verbose_name_plural': 'Квесты'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Время', 'verbose_name_plural': 'Время'},
        ),
        migrations.CreateModel(
            name='TimeForHorror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horror', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horrors_in_tfh', to='app_horror.horror', verbose_name='Квест')),
                ('times', models.ManyToManyField(blank=True, null=True, related_name='times_in_tfh', to='app_horror.timeslot', verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Время и квесты',
                'verbose_name_plural': 'Время и квесты',
            },
        ),
    ]
