# Generated by Django 5.1.7 on 2025-06-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0005_alter_booking_options_alter_horror_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundphotocard',
            options={'verbose_name': 'Задний фон для квеста', 'verbose_name_plural': 'Задний фон для квеста'},
        ),
        migrations.AlterModelOptions(
            name='blurphoto',
            options={'verbose_name': 'Логотип для квеста', 'verbose_name_plural': 'Логотип для квеста'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото квестов', 'verbose_name_plural': 'Фото квестов'},
        ),
    ]
