# Generated by Django 5.1.7 on 2025-08-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0006_alter_backgroundphotocard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bitrix_booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
