# Generated by Django 5.1.7 on 2025-09-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0007_booking_bitrix_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='horror',
            name='id_mir_kvestov',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
