# Generated by Django 5.1.7 on 2025-09-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0008_horror_id_mir_kvestov'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_id_mir_kvestov',
            field=models.CharField(blank=True, null=True),
        ),
    ]
