# Generated by Django 5.1.7 on 2025-09-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0009_booking_order_id_mir_kvestov'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_extrareality',
            field=models.CharField(blank=True, null=True),
        ),
    ]
