# Generated by Django 5.1.7 on 2025-09-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0010_booking_id_extrareality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id_extrareality',
        ),
        migrations.AddField(
            model_name='horror',
            name='id_extrareality',
            field=models.CharField(blank=True, null=True),
        ),
    ]
