# Generated by Django 5.1.7 on 2025-09-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0011_remove_booking_id_extrareality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_id_extrareality',
            field=models.CharField(blank=True, null=True),
        ),
    ]
