# Generated by Django 5.1.7 on 2025-10-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0013_booking_result_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundphotocard',
            options={'verbose_name': 'Логотип для квеста', 'verbose_name_plural': 'Логотип для квеста'},
        ),
        migrations.AlterModelOptions(
            name='blurphoto',
            options={'verbose_name': 'Задний фон для квеста', 'verbose_name_plural': 'Задний фон для квеста'},
        ),
    ]
