# Generated by Django 5.1.7 on 2025-10-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0014_alter_backgroundphotocard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='count_of_peoples',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=0, verbose_name='День'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='price',
            field=models.BigIntegerField(default=130),
        ),
    ]
