# Generated by Django 5.1.7 on 2025-10-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0015_timeslot_count_of_peoples_timeslot_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='count_of_peoples',
            field=models.IntegerField(default=1, verbose_name='Количество людей'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='price',
            field=models.BigIntegerField(default=130, verbose_name='цена'),
        ),
    ]
