# Generated by Django 5.1.7 on 2025-10-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0016_alter_timeslot_count_of_peoples_alter_timeslot_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=0, verbose_name='День'),
        ),
    ]
