# Generated by Django 5.1.7 on 2025-10-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0017_alter_timeslot_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.TimeField(),
        ),
    ]
