# Generated by Django 5.1.7 on 2025-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0018_alter_timeslot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='color',
            field=models.CharField(choices=[('0', 'Голубой'), ('1', 'Караловый'), ('2', 'Красный'), ('#ffd700', 'Золотистый')], default='#ffd700', verbose_name='Цвет ячейки'),
        ),
    ]
