# Generated by Django 5.1.7 on 2025-10-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0019_timeslot_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='count_of_peoples',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество человек'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='color',
            field=models.CharField(choices=[('#11B3D1', 'Голубой'), ('#0A8284', 'Караловый'), ('#A40000', 'Красный'), ('#ffd700', 'Золотистый')], default='#ffd700', verbose_name='Цвет ячейки'),
        ),
    ]
