# Generated by Django 5.1.7 on 2025-10-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0020_booking_count_of_peoples_alter_timeslot_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='horror',
            name='older_14',
            field=models.BooleanField(default=False, verbose_name='Необходимо чтоб все игроки были страше 14'),
        ),
    ]
