# Generated by Django 5.1.7 on 2025-10-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0021_horror_older_14'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Имя квеста'),
        ),
    ]
