# Generated by Django 5.1.7 on 2025-12-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horror', '0022_timeslot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='horror',
            name='blue_price',
            field=models.IntegerField(default=120, verbose_name='Голубая цена'),
        ),
        migrations.AddField(
            model_name='horror',
            name='caral_price',
            field=models.IntegerField(default=120, verbose_name='Караловая цена'),
        ),
        migrations.AddField(
            model_name='horror',
            name='red_price',
            field=models.IntegerField(default=120, verbose_name='Красная цена'),
        ),
    ]
